// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RakutenSearchController from "./rakuten_search_controller"
application.register("rakuten-search", RakutenSearchController)

import StretchAnalyzerController from "./stretch_analyzer_controller"
application.register("stretch-analyzer", StretchAnalyzerController)

import YoutubePreviewController from "./youtube_preview_controller"
application.register("youtube-preview", YoutubePreviewController)