:concurrency: 5
:scheduler:
  :schedule:
    check_inactive_users:
      cron: '0 12 * * *'
      class: CheckInactiveUsersJob
    sitemap_update:
      cron: '0 2 * * *'
      class: SitemapUpdateJob